baseURL = 'https://light-tech-talk.com/'
languageCode = 'en-us'
title = 'Light Tech Talk'
theme = 'hyde'

[taxonomies]
  tag = "tags"
  category = "categories"

# Enable rendering raw HTML in Markdown to avoid "Raw HTML omitted" warnings
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  description = """
No complexity — just LTT!<br>Light, simple short stories which will not in any case attach you to my writing.
<br>*By Edmond Cukalla"""

  [[params.social]]
    name = "x"
    url = "https://twitter.com/ecukalla"
    class = "fa-brands fa-x-twitter"

  [[params.social]]
    name = "github"
    url = "https://github.com/ecukalla"
    class = "fa-brands fa-github"

  [[params.social]]
    name = "strava"
    url = "https://strava.com/athletes/ecukalla"
    class = "fa-brands fa-strava"

  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/ecukalla"
    class = "fa-brands fa-linkedin-in"

  [[params.social]]
    name = "instagram"
    url = "https://www.instagram.com/ecukalla"
    class = "fa-brands fa-instagram"


  [params.meta]
    favicon = false

# Make all links absolute using baseURL
canonifyURLs = true

# Serve a proper robots.txt
enableRobotsTXT = true

# Optional but nice: clean permalinks for posts
[permalinks]
  posts = "/:slug/"

# Optional: tweak sitemap defaults (Hugo creates one by default)
[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[menus]
    main = [
        {Name = "Tags", URL = "/tags/", Weight = 3}
    ]