baseURL = 'light-tech-talk.com/'
languageCode = 'en-us'
title = 'Light Tech Talk'
theme = 'hyde'

# Use Hugo Modules to fetch the theme when building in CI
[module]
  [[module.imports]]
    path = "github.com/spf13/hyde"

[taxonomies]
  tag = "tags"
  category = "categories"

# Enable rendering raw HTML in Markdown to avoid "Raw HTML omitted" warnings
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  description = """
No complexity—just LTT!<br>Light, simple short stories which will not in any case attach you to my notes.
<br>*By Edmond Cukalla"""
